baseURL = "https://caldiss-aau.github.io/sdsphd21/"
languageCode = "en-us"
title = "AAU Social Data Science PhD 2021"
themesDir = "themes"
theme = "hugo-whisper-theme"
enableEmoji = true
relativeurls = false

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Materials & schedule"
    url = "/material/"
    weight = 2

[[menu.main]]
    name = "Info"
    url = "/info/"
    weight = 4
	
[[menu.main]]
	name = "Sessions"
	url = "/sessions/"
	weight = 3


[params]
  mainSections = ["material", "info", "sessions"]
  homepage_button_link = '/material'
  homepage_button_text = 'Go to the course material'
  homepage_image = '/images/aal_back.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "An Applied Introduction to Machine Learning for Social Science And Humanities Scholars"
    meta_og_title = "The Social Data Science PhD Course 2021"
    meta_og_type = "website"
    meta_og_url = "https://caldiss-aau.github.io/sdsphd21/"
    meta_og_description = "An Applied Introduction to Machine Learning for Social Science And Humanities Scholars"

  [params.logo]
      mobile = "/images/logo_aau.png"
      standard  = "/images/logo_aau.png"
